### ISSUE TITLE
Define PropTypes to avoid "unknown props on <time> tag" React warning message

### ISSUE THREAD

**Issue by empz** [martinandert/react-ago-component#1]
React 15.1.0 added the following warning

`Warning: Unknown props live, minPeriod, maxPeriod on <time> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop`

You should avoid passing down those props to the rendered `<time>` tag.

**Comment by martinandert** [comment]
The just released version 0.7.1 silences the warning for Ago's own properties (`date`, `tooltipFormat` and `autoUpdate`). Regarding the properties you pass to Ago (e.g. `live`, `minPeriod`, `maxPeriod`), https://fb.me/react-unknown-prop states that "When transferring props to a child component, you should ensure that you are not accidentally forwarding props that were intended to be interpreted by the parent component."

I consider this issue resolved. Feel free to re-open if need be.
